#!/usr/bin/env python3
"""Generate a minimal macOS .app bundle that registers the maya-mcp:// protocol handler.

The bundle contains:
  MCP Pipeline Console.app/
    Contents/
      Info.plist          — declares the URL scheme
      MacOS/
        mcp-console       — shell script that activates the venv and runs the Qt app

Usage:
  python -m console.build_app_bundle [--venv /path/to/.venv] [--output ~/Applications]
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
import textwrap
from pathlib import Path


APP_NAME = "MCP Pipeline Console"
BUNDLE_ID = "com.maya-mcp.pipeline-console"
URL_SCHEME = "maya-mcp"


def build_bundle(venv_dir: str, output_dir: str, project_dir: str) -> Path:
    """Create the .app bundle and return its path."""
    app_path = Path(output_dir) / f"{APP_NAME}.app"
    contents = app_path / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"

    macos.mkdir(parents=True, exist_ok=True)
    resources.mkdir(parents=True, exist_ok=True)

    # ---- Info.plist ----
    info_plist = contents / "Info.plist"
    info_plist.write_text(textwrap.dedent(f"""\
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleName</key>
            <string>{APP_NAME}</string>

            <key>CFBundleIdentifier</key>
            <string>{BUNDLE_ID}</string>

            <key>CFBundleVersion</key>
            <string>1.0</string>

            <key>CFBundleShortVersionString</key>
            <string>1.0</string>

            <key>CFBundleExecutable</key>
            <string>mcp-console</string>

            <key>CFBundlePackageType</key>
            <string>APPL</string>

            <key>LSBackgroundOnly</key>
            <false/>

            <key>CFBundleURLTypes</key>
            <array>
                <dict>
                    <key>CFBundleURLName</key>
                    <string>MCP Pipeline Protocol</string>
                    <key>CFBundleURLSchemes</key>
                    <array>
                        <string>{URL_SCHEME}</string>
                    </array>
                </dict>
            </array>
        </dict>
        </plist>
    """))

    # ---- Executable script ----
    executable = macos / "mcp-console"
    executable.write_text(textwrap.dedent(f"""\
        #!/bin/bash
        # Auto-generated by console.build_app_bundle
        # Activates the project venv and launches the unified MCP console.

        LOG="/tmp/mcp-console.log"
        exec >> "$LOG" 2>&1
        echo "=== $(date) === args: $@"

        export PATH="/usr/local/bin:/opt/homebrew/bin:$HOME/.npm-global/bin:$PATH"
        source "{venv_dir}/bin/activate"
        cd "{project_dir}"

        exec python3 -m console.app "$@"
    """))
    executable.chmod(executable.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    return app_path


def main():
    parser = argparse.ArgumentParser(description="Build MCP Pipeline Console .app bundle")
    parser.add_argument("--venv", type=str, default=None,
                        help="Path to .venv (default: auto-detect)")
    parser.add_argument("--output", type=str, default=None,
                        help="Output directory for .app (default: ~/Applications)")
    parser.add_argument("--project-dir", type=str, default=None,
                        help="Project root (default: auto-detect)")
    args = parser.parse_args()

    project_dir = os.path.abspath(
        args.project_dir or str(
            Path(__file__).resolve().parent.parent
        )
    )
    venv_dir = os.path.abspath(
        args.venv or os.path.join(project_dir, ".venv")
    )
    output_dir = os.path.abspath(
        args.output or os.path.expanduser("~/Applications")
    )

    if not os.path.isdir(venv_dir):
        print(f"Error: venv not found at {venv_dir}")
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    app_path = build_bundle(venv_dir, output_dir, project_dir)
    print(f"Built: {app_path}")
    print(f"Protocol handler: {URL_SCHEME}://")
    print()
    print("Register with macOS:")
    print(f"  open '{app_path}'  # first launch registers the URL scheme")
    print()
    print("Test:")
    print(f"  open 'maya-mcp://chat?entity_type=Asset&selected_ids=123&project_id=1244'")
    print()
    print("From Maya shelf (MEL):")
    print(f'  system("open \\"maya-mcp://chat\\"");')

    return str(app_path)


if __name__ == "__main__":
    main()
